In [1]:
# importing libraries

import twitter
import requests
import json
from datetime import datetime
import numpy as np
import pandas as pd

In [2]:
# bearer token

BEARER = 'XXX'

In [3]:
# get user id

uname = 'blvckfoxmedia'

headers_res1 = {
    'Authorization': 'Bearer ' + BEARER,
}

response = requests.get('https://api.twitter.com/2/users/by/username/' + uname, headers=headers_res1)

response_json = json.loads(response.text)

uid = response_json['data']['id']

In [4]:
# get phase dates

# Example Date: 14 May 2014

phase_1_date = '20 Jun 2022'
phase_2_date = '20 Oct 2022'
phase_3_date = '24 Mar 2023'

phase_1_date = datetime.strptime(phase_1_date, '%d %b %Y')
phase_2_date = datetime.strptime(phase_2_date, '%d %b %Y')
phase_3_date = datetime.strptime(phase_3_date, '%d %b %Y')

In [5]:
# get phase tweets

params_1 = {
    'end_time': phase_1_date.isoformat()+'Z',
    'tweet.fields' : 'created_at,text,attachments',
    'expansions' : 'author_id,attachments.media_keys',
    'media.fields' : 'media_key,type,url,variants,preview_image_url',
    'max_results' : 100
    
}

params_2 = {
    'end_time': phase_2_date.isoformat()+'Z',
    'tweet.fields' : 'created_at,text,attachments',
    'expansions' : 'author_id,attachments.media_keys',
    'media.fields' : 'media_key,type,url,variants,preview_image_url',
    'max_results' : 100
    
}

params_3 = {
    'end_time': phase_3_date.isoformat()+'Z',
    'tweet.fields' : 'created_at,text,attachments',
    'expansions' : 'author_id,attachments.media_keys',
    'media.fields' : 'media_key,type,url,variants,preview_image_url',
    'max_results' : 100
    
}

headers_res2 = {
    'Authorization': 'Bearer ' + BEARER,
}

tweets_response_1 = requests.get('https://api.twitter.com/2/users/' + uid + '/tweets', params=params_1, headers=headers_res2)
tweets_response_2 = requests.get('https://api.twitter.com/2/users/' + uid + '/tweets', params=params_2, headers=headers_res2)
tweets_response_3 = requests.get('https://api.twitter.com/2/users/' + uid + '/tweets', params=params_3, headers=headers_res2)

tweets_json_1 = json.loads(tweets_response_1.text)
tweets_json_2 = json.loads(tweets_response_2.text)
tweets_json_3 = json.loads(tweets_response_3.text)

In [6]:
# extracting info from tweets

mobs = []

for item in tweets_json_1['includes']['media']:
    
    row = []
    
    if 'photo' in str(item):
        row.append(item['media_key'])
        row.append('photo')
        row.append(item['url'])
    
    if 'video' in str(item):
        row.append(item['media_key'])
        for subitem in item['variants']:
            try:
                if subitem['bit_rate'] == 2176000:
                    row.append('video')
                    row.append(subitem['url'])
            except:
                pass

    mobs.append(row)

for item in tweets_json_2['includes']['media']:
    
    row = []
    
    if 'photo' in str(item):
        row.append(item['media_key'])
        row.append('photo')
        row.append(item['url'])
    
    if 'video' in str(item):
        row.append(item['media_key'])
        for subitem in item['variants']:
            try:
                if subitem['bit_rate'] == 2176000:
                    row.append('video')
                    row.append(subitem['url'])
            except:
                pass

    mobs.append(row)

for item in tweets_json_3['includes']['media']:
    
    row = []
    
    if 'photo' in str(item):
        row.append(item['media_key'])
        row.append('photo')
        row.append(item['url'])
    
    if 'video' in str(item):
        row.append(item['media_key'])
        for subitem in item['variants']:
            try:
                if subitem['bit_rate'] == 2176000:
                    row.append('video')
                    row.append(subitem['url'])
            except:
                pass

    mobs.append(row)

obs = []

for item in tweets_json_1['data']:
    row = [uid]
    row.append(item['created_at'])
    row.append(item['text'])
    
    try:
        if 'media_key' in str(item):
            if len(item['attachments']['media_keys']) == 1:
                for media_key in item['attachments']['media_keys']:
                    row.append(media_key)
            else:
                for i in range(len(item['attachments']['media_keys'])):
                    spl_row = [uid]
                    spl_row.append(item['created_at'])
                    spl_row.append(item['text'])
                    spl_row.append(item['attachments']['media_keys'][i])
                    obs.append(spl_row)
        else:
            row.append(0)
            
    except:
        pass
    
    obs.append(row)
    
for item in tweets_json_2['data']:
    row = [uid]
    row.append(item['created_at'])
    row.append(item['text'])
    
    try:
        if 'media_key' in str(item):
            if len(item['attachments']['media_keys']) == 1:
                for media_key in item['attachments']['media_keys']:
                    row.append(media_key)
            else:
                for i in range(len(item['attachments']['media_keys'])):
                    spl_row = [uid]
                    spl_row.append(item['created_at'])
                    spl_row.append(item['text'])
                    spl_row.append(item['attachments']['media_keys'][i])
                    obs.append(spl_row)
        else:
            row.append(0)
            
    except:
        pass
    
    obs.append(row)
    
for item in tweets_json_3['data']:
    row = [uid]
    row.append(item['created_at'])
    row.append(item['text'])
    
    try:
        if 'media_key' in str(item):
            if len(item['attachments']['media_keys']) == 1:
                for media_key in item['attachments']['media_keys']:
                    row.append(media_key)
            else:
                for i in range(len(item['attachments']['media_keys'])):
                    spl_row = [uid]
                    spl_row.append(item['created_at'])
                    spl_row.append(item['text'])
                    spl_row.append(item['attachments']['media_keys'][i])
                    obs.append(spl_row)
        else:
            row.append(0)
            
    except:
        pass
    
    obs.append(row)

In [7]:
# create a dataFrame object

df = pd.DataFrame(columns = ['user_id' , 'created_at', 'text' , 'media_key'])
df = df.append(pd.DataFrame(obs,
               columns=[ 'user_id', 'created_at', 'text', 'media_key']),
               ignore_index = True)
df = df.dropna()
df.reset_index(inplace=True)

m_df = pd.DataFrame(columns = ['media_key' , 'content_type', 'url'])
m_df = m_df.append(pd.DataFrame(mobs,
               columns = ['media_key' , 'content_type', 'url']),
               ignore_index = True)

user_df = pd.merge(
    df, m_df, how='outer', on=['media_key']
)
user_df

C:\Users\Suhet\AppData\Local\Temp\ipykernel_44620\1426585972.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(pd.DataFrame(obs,
C:\Users\Suhet\AppData\Local\Temp\ipykernel_44620\1426585972.py:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  m_df = m_df.append(pd.DataFrame(mobs,

,index,user_id,created_at,text,media_key,content_type,url
0,0,3496700832,2022-06-19T23:27:38.000Z,"RT @LeoTerms: It wont impress her, but a gift ...",0,NaN,NaN
1,1,3496700832,2022-06-19T23:26:51.000Z,he already a dad but I’m bout to make him a da...,0,NaN,NaN
2,3,3496700832,2022-06-19T19:14:52.000Z,RT @kcamp: I just wanna get $ be creative &amp...,0,NaN,NaN
3,5,3496700832,2022-06-19T08:00:36.000Z,y’all get an attitude when you miss your boo t...,0,NaN,NaN
4,7,3496700832,2022-06-18T06:37:15.000Z,RT @death2amerikkka: People (men especially) a...,0,NaN,NaN
...,...,...,...,...,...,...,...
321,331,3496700832,2023-03-19T00:30:10.000Z,i 💘 these guys sm 🥺 https://t.co/34okGLB250,3_1637250045300080640,photo,https://pbs.twimg.com/media/FriuPd6agAAFGmX.jpg
322,332,3496700832,2023-03-19T00:30:10.000Z,i 💘 these guys sm 🥺 https://t.co/34okGLB250,3_1637250045312651264,photo,https://pbs.twimg.com/media/FriuPd9aUAAHz46.jpg
323,333,3496700832,2023-03-19T00:30:10.000Z,i 💘 these guys sm 🥺 https://t.co/34okGLB250,3_1637250045304258560,photo,https://pbs.twimg.com/media/FriuPd7aQAADJUt.jpg
324,335,3496700832,2023-03-18T22:59:52.000Z,RT @StreetFashion01: https://t.co/yb8zQ8yzXw,3_1637060117811036160,photo,https://pbs.twimg.com/media/FrgBgO4WAAAD8ZG.jpg
325,338,3496700832,2023-03-18T22:57:03.000Z,RT @jimmyoutsold: mr krabs trying to get that ...,7_1560296786572369921,video,https://video.twimg.com/ext_tw_video/156029678...

In [8]:
# categorizing phases

user_df['created_at'] = user_df['created_at'].map(lambda x: datetime.strptime(x, "%Y-%m-%dT%H:%M:%S.000Z"))

conditions = [
    (user_df['created_at'] < phase_1_date),
    (user_df['created_at'] >= phase_1_date) & (user_df['created_at'] < phase_2_date),
    (user_df['created_at'] >= phase_2_date) & (user_df['created_at'] < phase_3_date),
    (user_df['created_at'] >= phase_3_date)
]

values = [1, 2, 3, 3]

user_df['phase'] = np.select(conditions, values)

In [9]:
# dropping duplicates in cases of tweet overlaps and phase counts

user_df = user_df.drop_duplicates()

user_df['phase'].value_counts()

2    110
1    108
3    108
Name: phase, dtype: int64

In [10]:
# final df

user_df

,index,user_id,created_at,text,media_key,content_type,url,phase
0,0,3496700832,2022-06-19 23:27:38,"RT @LeoTerms: It wont impress her, but a gift ...",0,NaN,NaN,1
1,1,3496700832,2022-06-19 23:26:51,he already a dad but I’m bout to make him a da...,0,NaN,NaN,1
2,3,3496700832,2022-06-19 19:14:52,RT @kcamp: I just wanna get $ be creative &amp...,0,NaN,NaN,1
3,5,3496700832,2022-06-19 08:00:36,y’all get an attitude when you miss your boo t...,0,NaN,NaN,1
4,7,3496700832,2022-06-18 06:37:15,RT @death2amerikkka: People (men especially) a...,0,NaN,NaN,1
...,...,...,...,...,...,...,...,...
321,331,3496700832,2023-03-19 00:30:10,i 💘 these guys sm 🥺 https://t.co/34okGLB250,3_1637250045300080640,photo,https://pbs.twimg.com/media/FriuPd6agAAFGmX.jpg,3
322,332,3496700832,2023-03-19 00:30:10,i 💘 these guys sm 🥺 https://t.co/34okGLB250,3_1637250045312651264,photo,https://pbs.twimg.com/media/FriuPd9aUAAHz46.jpg,3
323,333,3496700832,2023-03-19 00:30:10,i 💘 these guys sm 🥺 https://t.co/34okGLB250,3_1637250045304258560,photo,https://pbs.twimg.com/media/FriuPd7aQAADJUt.jpg,3
324,335,3496700832,2023-03-18 22:59:52,RT @StreetFashion01: https://t.co/yb8zQ8yzXw,3_1637060117811036160,photo,https://pbs.twimg.com/media/FrgBgO4WAAAD8ZG.jpg,3
325,338,3496700832,2023-03-18 22:57:03,RT @jimmyoutsold: mr krabs trying to get that ...,7_1560296786572369921,video,https://video.twimg.com/ext_tw_video/156029678...,3

In [11]:
# media count

user_df['content_type'].value_counts()

photo    82
video    16
Name: content_type, dtype: int64